import { PokemonObject } from '@/interfaces/pokemon';

export const kantoPokemon: PokemonObject[] = [
  {
    id: 1,
    name: 'Bulbasaur',
    slug: 'bulbasaur',
    types: ['grass', 'poison'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 0.875,
      female: 0.125,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: [],
  },
  {
    id: 2,
    name: 'Ivysaur',
    slug: 'ivysaur',
    types: ['grass', 'poison'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 0.875,
      female: 0.125,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: [],
  },
  {
    id: 3,
    name: 'Venusaur',
    slug: 'venusaur',
    types: ['grass', 'poison'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 0.875,
      female: 0.125,
    },
    hasFemaleImage: true,
    activeSpawn: 'day',
    variants: ['mega'],
  },
  {
    id: 4,
    name: 'Charmander',
    slug: 'charmander',
    types: ['fire'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 0.875,
      female: 0.125,
    },
    hasFemaleImage: false,
    activeSpawn: 'both',
    variants: [],
  },
  {
    id: 5,
    name: 'Charmeleon',
    slug: 'charmeleon',
    types: ['fire'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 0.875,
      female: 0.125,
    },
    hasFemaleImage: false,
    activeSpawn: 'both',
    variants: [],
  },
  {
    id: 6,
    name: 'Charizard',
    slug: 'charizard',
    types: ['fire', 'flying'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 0.875,
      female: 0.125,
    },
    hasFemaleImage: false,
    activeSpawn: 'night',
    variants: ['megax', 'megay'],
  },
  {
    id: 7,
    name: 'Squirtle',
    slug: 'squirtle',
    types: ['water'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 0.875,
      female: 0.125,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: [],
  },
  {
    id: 8,
    name: 'Wartortle',
    slug: 'wartortle',
    types: ['water'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 0.875,
      female: 0.125,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: [],
  },
  {
    id: 9,
    name: 'Blastoise',
    slug: 'blastoise',
    types: ['water'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 0.875,
      female: 0.125,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: ['mega'],
  },
  {
    id: 10,
    name: 'Caterpie',
    slug: 'caterpie',
    types: ['bug'],
    rarity: 'common',
    catchRate: 255,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: [],
  },
  {
    id: 11,
    name: 'Metapod',
    slug: 'metapod',
    types: ['bug'],
    rarity: 'uncommon',
    catchRate: 120,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: [],
  },
  {
    id: 12,
    name: 'Butterfree',
    slug: 'butterfree',
    types: ['bug', 'flying'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: true,
    activeSpawn: 'day',
    variants: [],
  },
  {
    id: 13,
    name: 'Weedle',
    slug: 'weedle',
    types: ['bug', 'poison'],
    rarity: 'common',
    catchRate: 255,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: [],
  },
  {
    id: 14,
    name: 'Kakuna',
    slug: 'kakuna',
    types: ['bug', 'poison'],
    rarity: 'uncommon',
    catchRate: 120,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: [],
  },
  {
    id: 15,
    name: 'Beedrill',
    slug: 'beedrill',
    types: ['bug', 'poison'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'both',
    variants: ['mega'],
  },
  {
    id: 16,
    name: 'Pidgey',
    slug: 'pidgey',
    types: ['normal', 'flying'],
    rarity: 'common',
    catchRate: 255,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: [],
  },
  {
    id: 17,
    name: 'Pidgeotto',
    slug: 'pidgeotto',
    types: ['normal', 'flying'],
    rarity: 'uncommon',
    catchRate: 120,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: [],
  },
  {
    id: 18,
    name: 'Pidgeot',
    slug: 'pidgeot',
    types: ['normal', 'flying'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: ['mega'],
  },
  {
    id: 19,
    name: 'Rattata',
    slug: 'rattata',
    types: ['normal'],
    rarity: 'common',
    catchRate: 255,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: true,
    activeSpawn: 'both',
    variants: ['alolan'],
  },
  {
    id: 20,
    name: 'Raticate',
    slug: 'raticate',
    types: ['normal'],
    rarity: 'uncommon',
    catchRate: 127,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: true,
    activeSpawn: 'night',
    variants: ['alolan'],
  },
  {
    id: 21,
    name: 'Spearow',
    slug: 'spearow',
    types: ['normal', 'flying'],
    rarity: 'common',
    catchRate: 255,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'both',
    variants: [],
  },
  {
    id: 22,
    name: 'Fearow',
    slug: 'fearow',
    types: ['normal', 'flying'],
    rarity: 'rare',
    catchRate: 90,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: [],
  },
  {
    id: 23,
    name: 'Ekans',
    slug: 'ekans',
    types: ['poison'],
    rarity: 'common',
    catchRate: 255,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'both',
    variants: [],
  },
  {
    id: 24,
    name: 'Arbok',
    slug: 'arbok',
    types: ['poison'],
    rarity: 'rare',
    catchRate: 90,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'both',
    variants: [],
  },
  {
    id: 25,
    name: 'Pikachu',
    slug: 'pikachu',
    types: ['electric'],
    rarity: 'common',
    catchRate: 190,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: true,
    activeSpawn: 'day',
    variants: [],
  },
  {
    id: 26,
    name: 'Raichu',
    slug: 'raichu',
    types: ['electric'],
    rarity: 'rare',
    catchRate: 75,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: true,
    activeSpawn: 'day',
    variants: ['alolan'],
  },
  {
    id: 27,
    name: 'Sandshrew',
    slug: 'sandshrew',
    types: ['ground'],
    rarity: 'common',
    catchRate: 255,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: ['alolan'],
  },
  {
    id: 28,
    name: 'Sandslash',
    slug: 'sandslash',
    types: ['ground'],
    rarity: 'rare',
    catchRate: 90,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: ['alolan'],
  },
  {
    id: 29,
    name: 'Nidoran ♀',
    slug: 'nidoran-f',
    types: ['poison'],
    rarity: 'common',
    catchRate: 235,
    genderRatio: {
      male: 0,
      female: 1,
    },
    hasFemaleImage: false,
    activeSpawn: 'both',
    variants: [],
  },
  {
    id: 30,
    name: 'Nidorina',
    slug: 'nidorina',
    types: ['poison'],
    rarity: 'uncommon',
    catchRate: 120,
    genderRatio: {
      male: 0,
      female: 1,
    },
    hasFemaleImage: false,
    activeSpawn: 'both',
    variants: [],
  },
  {
    id: 31,
    name: 'Nidoqueen',
    slug: 'nidoqueen',
    types: ['poison', 'ground'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 0,
      female: 1,
    },
    hasFemaleImage: false,
    activeSpawn: 'both',
    variants: [],
  },
  {
    id: 32,
    name: 'Nidoran ♂',
    slug: 'nidoran-m',
    types: ['poison'],
    rarity: 'common',
    catchRate: 235,
    genderRatio: {
      male: 1,
      female: 0,
    },
    hasFemaleImage: false,
    activeSpawn: 'both',
    variants: [],
  },
  {
    id: 33,
    name: 'Nidorino',
    slug: 'nidorino',
    types: ['poison'],
    rarity: 'uncommon',
    catchRate: 120,
    genderRatio: {
      male: 1,
      female: 0,
    },
    hasFemaleImage: false,
    activeSpawn: 'both',
    variants: [],
  },
  {
    id: 34,
    name: 'Nidoking',
    slug: 'nidoking',
    types: ['poison', 'ground'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 1,
      female: 0,
    },
    hasFemaleImage: false,
    activeSpawn: 'both',
    variants: [],
  },
  {
    id: 35,
    name: 'Clefairy',
    slug: 'clefairy',
    types: ['fairy'],
    rarity: 'uncommon',
    catchRate: 150,
    genderRatio: {
      male: 0.25,
      female: 0.75,
    },
    hasFemaleImage: false,
    activeSpawn: 'both',
    variants: [],
  },
  {
    id: 36,
    name: 'Clefable',
    slug: 'clefable',
    types: ['fairy'],
    rarity: 'very rare',
    catchRate: 25,
    genderRatio: {
      male: 0.25,
      female: 0.75,
    },
    hasFemaleImage: false,
    activeSpawn: 'both',
    variants: ['mega'],
  },
  {
    id: 37,
    name: 'Vulpix',
    slug: 'vulpix',
    types: ['fire'],
    rarity: 'common',
    catchRate: 190,
    genderRatio: {
      male: 0.25,
      female: 0.75,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: ['alolan'],
  },
  {
    id: 38,
    name: 'Ninetales',
    slug: 'ninetales',
    types: ['fire'],
    rarity: 'rare',
    catchRate: 75,
    genderRatio: {
      male: 0.25,
      female: 0.75,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: ['alolan'],
  },
  {
    id: 39,
    name: 'Jigglypuff',
    slug: 'jigglypuff',
    types: ['normal', 'fairy'],
    rarity: 'uncommon',
    catchRate: 170,
    genderRatio: {
      male: 0.25,
      female: 0.75,
    },
    hasFemaleImage: false,
    activeSpawn: 'both',
    variants: [],
  },
  {
    id: 40,
    name: 'Wigglytuff',
    slug: 'wigglytuff',
    types: ['normal', 'fairy'],
    rarity: 'rare',
    catchRate: 50,
    genderRatio: {
      male: 0.25,
      female: 0.75,
    },
    hasFemaleImage: false,
    activeSpawn: 'both',
    variants: [],
  },
  {
    id: 41,
    name: 'Zubat',
    slug: 'zubat',
    types: ['poison', 'flying'],
    rarity: 'common',
    catchRate: 255,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: true,
    activeSpawn: 'both',
    variants: [],
  },
  {
    id: 42,
    name: 'Golbat',
    slug: 'golbat',
    types: ['poison', 'flying'],
    rarity: 'rare',
    catchRate: 90,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: true,
    activeSpawn: 'both',
    variants: [],
  },
  {
    id: 43,
    name: 'Oddish',
    slug: 'oddish',
    types: ['grass', 'poison'],
    rarity: 'common',
    catchRate: 255,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'night',
    variants: [],
  },
  {
    id: 44,
    name: 'Gloom',
    slug: 'gloom',
    types: ['grass', 'poison'],
    rarity: 'uncommon',
    catchRate: 120,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: true,
    activeSpawn: 'night',
    variants: [],
  },
  {
    id: 45,
    name: 'Vileplume',
    slug: 'vileplume',
    types: ['grass', 'poison'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: true,
    activeSpawn: 'night',
    variants: [],
  },
  {
    id: 46,
    name: 'Paras',
    slug: 'paras',
    types: ['bug', 'grass'],
    rarity: 'common',
    catchRate: 190,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: [],
  },
  {
    id: 47,
    name: 'Parasect',
    slug: 'parasect',
    types: ['bug', 'grass'],
    rarity: 'rare',
    catchRate: 75,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: [],
  },
  {
    id: 48,
    name: 'Venonat',
    slug: 'venonat',
    types: ['bug', 'poison'],
    rarity: 'common',
    catchRate: 190,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'both',
    variants: [],
  },
  {
    id: 49,
    name: 'Venomoth',
    slug: 'venomoth',
    types: ['bug', 'poison'],
    rarity: 'rare',
    catchRate: 75,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'night',
    variants: [],
  },
  {
    id: 50,
    name: 'Diglett',
    slug: 'diglett',
    types: ['ground'],
    rarity: 'common',
    catchRate: 255,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'both',
    variants: ['alolan'],
  },
  {
    id: 51,
    name: 'Dugtrio',
    slug: 'dugtrio',
    types: ['ground'],
    rarity: 'rare',
    catchRate: 50,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'night',
    variants: ['alolan'],
  },
  {
    id: 52,
    name: 'Meowth',
    slug: 'meowth',
    types: ['normal'],
    rarity: 'common',
    catchRate: 255,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'both',
    variants: ['alolan', 'galarian'],
  },
  {
    id: 53,
    name: 'Persian',
    slug: 'persian',
    types: ['normal'],
    rarity: 'rare',
    catchRate: 90,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'night',
    variants: ['alolan'],
  },
  {
    id: 54,
    name: 'Psyduck',
    slug: 'psyduck',
    types: ['water'],
    rarity: 'common',
    catchRate: 190,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'night',
    variants: [],
  },
  {
    id: 55,
    name: 'Golduck',
    slug: 'golduck',
    types: ['water'],
    rarity: 'rare',
    catchRate: 75,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'night',
    variants: [],
  },
  {
    id: 56,
    name: 'Mankey',
    slug: 'mankey',
    types: ['fighting'],
    rarity: 'common',
    catchRate: 190,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: [],
  },
  {
    id: 57,
    name: 'Primeape',
    slug: 'primeape',
    types: ['fighting'],
    rarity: 'rare',
    catchRate: 75,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: [],
  },
  {
    id: 58,
    name: 'Growlithe',
    slug: 'growlithe',
    types: ['fire'],
    rarity: 'common',
    catchRate: 190,
    genderRatio: {
      male: 0.75,
      female: 0.25,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: ['hisuian'],
  },
  {
    id: 59,
    name: 'Arcanine',
    slug: 'arcanine',
    types: ['fire'],
    rarity: 'rare',
    catchRate: 75,
    genderRatio: {
      male: 0.75,
      female: 0.25,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: ['hisuian'],
  },
  {
    id: 60,
    name: 'Poliwag',
    slug: 'poliwag',
    types: ['water'],
    rarity: 'common',
    catchRate: 255,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'night',
    variants: [],
  },
  {
    id: 61,
    name: 'Poliwhirl',
    slug: 'poliwhirl',
    types: ['water'],
    rarity: 'uncommon',
    catchRate: 120,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'night',
    variants: [],
  },
  {
    id: 62,
    name: 'Poliwrath',
    slug: 'poliwrath',
    types: ['water', 'fighting'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'night',
    variants: [],
  },
  {
    id: 63,
    name: 'Abra',
    slug: 'abra',
    types: ['psychic'],
    rarity: 'common',
    catchRate: 200,
    genderRatio: {
      male: 0.75,
      female: 0.25,
    },
    hasFemaleImage: false,
    activeSpawn: 'both',
    variants: [],
  },
  {
    id: 64,
    name: 'Kadabra',
    slug: 'kadabra',
    types: ['psychic'],
    rarity: 'rare',
    catchRate: 100,
    genderRatio: {
      male: 0.75,
      female: 0.25,
    },
    hasFemaleImage: true,
    activeSpawn: 'day',
    variants: [],
  },
  {
    id: 65,
    name: 'Alakazam',
    slug: 'alakazam',
    types: ['psychic'],
    rarity: 'rare',
    catchRate: 50,
    genderRatio: {
      male: 0.75,
      female: 0.25,
    },
    hasFemaleImage: true,
    activeSpawn: 'night',
    variants: ['mega'],
  },
  {
    id: 66,
    name: 'Machop',
    slug: 'machop',
    types: ['fighting'],
    rarity: 'uncommon',
    catchRate: 180,
    genderRatio: {
      male: 0.75,
      female: 0.25,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: [],
  },
  {
    id: 67,
    name: 'Machoke',
    slug: 'machoke',
    types: ['fighting'],
    rarity: 'rare',
    catchRate: 90,
    genderRatio: {
      male: 0.75,
      female: 0.25,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: [],
  },
  {
    id: 68,
    name: 'Machamp',
    slug: 'machamp',
    types: ['fighting'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 0.75,
      female: 0.25,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: [],
  },
  {
    id: 69,
    name: 'Bellsprout',
    slug: 'bellsprout',
    types: ['grass', 'poison'],
    rarity: 'common',
    catchRate: 255,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: [],
  },
  {
    id: 70,
    name: 'Weepinbell',
    slug: 'weepinbell',
    types: ['grass', 'poison'],
    rarity: 'uncommon',
    catchRate: 120,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: [],
  },
  {
    id: 71,
    name: 'Victreebel',
    slug: 'victreebel',
    types: ['grass', 'poison'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'both',
    variants: ['mega'],
  },
  {
    id: 72,
    name: 'Tentacool',
    slug: 'tentacool',
    types: ['water', 'poison'],
    rarity: 'common',
    catchRate: 190,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'night',
    variants: [],
  },
  {
    id: 73,
    name: 'Tentacruel',
    slug: 'tentacruel',
    types: ['water', 'poison'],
    rarity: 'rare',
    catchRate: 60,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'night',
    variants: [],
  },
  {
    id: 74,
    name: 'Geodude',
    slug: 'geodude',
    types: ['rock', 'ground'],
    rarity: 'common',
    catchRate: 255,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'both',
    variants: ['alolan'],
  },
  {
    id: 75,
    name: 'Graveler',
    slug: 'graveler',
    types: ['rock', 'ground'],
    rarity: 'uncommon',
    catchRate: 120,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'both',
    variants: ['alolan'],
  },
  {
    id: 76,
    name: 'Golem',
    slug: 'golem',
    types: ['rock', 'ground'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'both',
    variants: ['alolan'],
  },
  {
    id: 77,
    name: 'Ponyta',
    slug: 'ponyta',
    types: ['fire'],
    rarity: 'common',
    catchRate: 190,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: ['galarian'],
  },
  {
    id: 78,
    name: 'Rapidash',
    slug: 'rapidash',
    types: ['fire'],
    rarity: 'rare',
    catchRate: 60,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: ['galarian'],
  },
  {
    id: 79,
    name: 'Slowpoke',
    slug: 'slowpoke',
    types: ['water', 'psychic'],
    rarity: 'common',
    catchRate: 190,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: ['galarian'],
  },
  {
    id: 80,
    name: 'Slowbro',
    slug: 'slowbro',
    types: ['water', 'psychic'],
    rarity: 'rare',
    catchRate: 75,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'night',
    variants: ['glarian', 'mega'],
  },
  {
    id: 81,
    name: 'Magnemite',
    slug: 'magnemite',
    types: ['electric', 'steel'],
    rarity: 'common',
    catchRate: 190,
    genderRatio: null,
    hasFemaleImage: false,
    activeSpawn: 'both',
    variants: [],
  },
  {
    id: 82,
    name: 'Magneton',
    slug: 'magneton',
    types: ['electric', 'steel'],
    rarity: 'rare',
    catchRate: 60,
    genderRatio: null,
    hasFemaleImage: false,
    activeSpawn: 'both',
    variants: [],
  },
  {
    id: 83,
    name: 'Farfetchd',
    slug: 'farfetchd',
    types: ['normal', 'flying'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: ['galarian'],
  },
  {
    id: 84,
    name: 'Doduo',
    slug: 'doduo',
    types: ['normal', 'flying'],
    rarity: 'common',
    catchRate: 190,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: true,
    activeSpawn: 'day',
    variants: [],
  },
  {
    id: 85,
    name: 'Dodrio',
    slug: 'dodrio',
    types: ['normal', 'flying'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: true,
    activeSpawn: 'day',
    variants: [],
  },
  {
    id: 86,
    name: 'Seel',
    slug: 'seel',
    types: ['water'],
    rarity: 'common',
    catchRate: 190,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'both',
    variants: [],
  },
  {
    id: 87,
    name: 'Dewgong',
    slug: 'dewgong',
    types: ['water', 'ice'],
    rarity: 'rare',
    catchRate: 75,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: [],
  },
  {
    id: 88,
    name: 'Grimer',
    slug: 'grimer',
    types: ['poison'],
    rarity: 'common',
    catchRate: 190,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'both',
    variants: ['alolan'],
  },
  {
    id: 89,
    name: 'Muk',
    slug: 'muk',
    types: ['poison'],
    rarity: 'rare',
    catchRate: 75,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'both',
    variants: ['alolan'],
  },
  {
    id: 90,
    name: 'Shellder',
    slug: 'shellder',
    types: ['water'],
    rarity: 'common',
    catchRate: 190,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'both',
    variants: [],
  },
  {
    id: 91,
    name: 'Cloyster',
    slug: 'cloyster',
    types: ['water', 'ice'],
    rarity: 'rare',
    catchRate: 60,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'night',
    variants: [],
  },
  {
    id: 92,
    name: 'Gastly',
    slug: 'gastly',
    types: ['ghost', 'poison'],
    rarity: 'common',
    catchRate: 190,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'night',
    variants: [],
  },
  {
    id: 93,
    name: 'Haunter',
    slug: 'haunter',
    types: ['ghost', 'poison'],
    rarity: 'rare',
    catchRate: 90,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'night',
    variants: [],
  },
  {
    id: 94,
    name: 'Gengar',
    slug: 'gengar',
    types: ['ghost', 'poison'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'night',
    variants: ['mega'],
  },
  {
    id: 95,
    name: 'Onix',
    slug: 'onix',
    types: ['rock', 'ground'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: [],
  },
  {
    id: 96,
    name: 'Drowzee',
    slug: 'drowzee',
    types: ['psychic'],
    rarity: 'common',
    catchRate: 190,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'night',
    variants: [],
  },
  {
    id: 97,
    name: 'Hypno',
    slug: 'hypno',
    types: ['psychic'],
    rarity: 'rare',
    catchRate: 75,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: true,
    activeSpawn: 'night',
    variants: [],
  },
  {
    id: 98,
    name: 'Krabby',
    slug: 'krabby',
    types: ['water'],
    rarity: 'common',
    catchRate: 225,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: [],
  },
  {
    id: 99,
    name: 'Kingler',
    slug: 'kingler',
    types: ['water'],
    rarity: 'rare',
    catchRate: 60,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: [],
  },
  {
    id: 100,
    name: 'Voltorb',
    slug: 'voltorb',
    types: ['electric'],
    rarity: 'common',
    catchRate: 190,
    genderRatio: null,
    hasFemaleImage: false,
    activeSpawn: 'both',
    variants: ['hisuian'],
  },
  {
    id: 101,
    name: 'Electrode',
    slug: 'electrode',
    types: ['electric'],
    rarity: 'rare',
    catchRate: 60,
    genderRatio: null,
    hasFemaleImage: false,
    activeSpawn: 'both',
    variants: ['hisuian'],
  },
  {
    id: 102,
    name: 'Exeggcute',
    slug: 'exeggcute',
    types: ['grass', 'psychic'],
    rarity: 'rare',
    catchRate: 90,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: [],
  },
  {
    id: 103,
    name: 'Exeggutor',
    slug: 'exeggutor',
    types: ['grass', 'psychic'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: ['alolan'],
  },
  {
    id: 104,
    name: 'Cubone',
    slug: 'cubone',
    types: ['ground'],
    rarity: 'common',
    catchRate: 190,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'both',
    variants: [],
  },
  {
    id: 105,
    name: 'Marowak',
    slug: 'marowak',
    types: ['ground'],
    rarity: 'rare',
    catchRate: 75,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'both',
    variants: ['alolan'],
  },
  {
    id: 106,
    name: 'Hitmonlee',
    slug: 'hitmonlee',
    types: ['fighting'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 1,
      female: 0,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: [],
  },
  {
    id: 107,
    name: 'Hitmonchan',
    slug: 'hitmonchan',
    types: ['fighting'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 1,
      female: 0,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: [],
  },
  {
    id: 108,
    name: 'Lickitung',
    slug: 'lickitung',
    types: ['normal'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'both',
    variants: [],
  },
  {
    id: 109,
    name: 'Koffing',
    slug: 'koffing',
    types: ['poison'],
    rarity: 'common',
    catchRate: 190,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'both',
    variants: [],
  },
  {
    id: 110,
    name: 'Weezing',
    slug: 'weezing',
    types: ['poison'],
    rarity: 'rare',
    catchRate: 60,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: ['galarian'],
  },
  {
    id: 111,
    name: 'Rhyhorn',
    slug: 'rhyhorn',
    types: ['ground', 'rock'],
    rarity: 'uncommon',
    catchRate: 120,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: true,
    activeSpawn: 'day',
    variants: [],
  },
  {
    id: 112,
    name: 'Rhydon',
    slug: 'rhydon',
    types: ['ground', 'rock'],
    rarity: 'rare',
    catchRate: 60,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: true,
    activeSpawn: 'day',
    variants: [],
  },
  {
    id: 113,
    name: 'Chansey',
    slug: 'chansey',
    types: ['normal'],
    rarity: 'very rare',
    catchRate: 30,
    genderRatio: {
      male: 0,
      female: 1,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: [],
  },
  {
    id: 114,
    name: 'Tangela',
    slug: 'tangela',
    types: ['grass'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'both',
    variants: [],
  },
  {
    id: 115,
    name: 'Kangaskhan',
    slug: 'kangaskhan',
    types: ['normal'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 0,
      female: 1,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: ['mega'],
  },
  {
    id: 116,
    name: 'Horsea',
    slug: 'horsea',
    types: ['water'],
    rarity: 'common',
    catchRate: 225,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: [],
  },
  {
    id: 117,
    name: 'Seadra',
    slug: 'seadra',
    types: ['water'],
    rarity: 'rare',
    catchRate: 75,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: [],
  },
  {
    id: 118,
    name: 'Goldeen',
    slug: 'goldeen',
    types: ['water'],
    rarity: 'common',
    catchRate: 225,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: true,
    activeSpawn: 'both',
    variants: [],
  },
  {
    id: 119,
    name: 'Seaking',
    slug: 'seaking',
    types: ['water'],
    rarity: 'rare',
    catchRate: 60,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: true,
    activeSpawn: 'both',
    variants: [],
  },
  {
    id: 120,
    name: 'Staryu',
    slug: 'staryu',
    types: ['water'],
    rarity: 'common',
    catchRate: 225,
    genderRatio: null,
    hasFemaleImage: false,
    activeSpawn: 'night',
    variants: [],
  },
  {
    id: 121,
    name: 'Starmie',
    slug: 'starmie',
    types: ['water', 'psychic'],
    rarity: 'rare',
    catchRate: 60,
    genderRatio: null,
    hasFemaleImage: false,
    activeSpawn: 'night',
    variants: ['mega'],
  },
  {
    id: 122,
    name: 'Mr. Mime',
    slug: 'mr-mime',
    types: ['psychic', 'fairy'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: ['galarian'],
  },
  {
    id: 123,
    name: 'Scyther',
    slug: 'scyther',
    types: ['bug', 'flying'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: true,
    activeSpawn: 'day',
    variants: [],
  },
  {
    id: 124,
    name: 'Jynx',
    slug: 'jynx',
    types: ['ice', 'psychic'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 0,
      female: 1,
    },
    hasFemaleImage: false,
    activeSpawn: 'night',
    variants: [],
  },
  {
    id: 125,
    name: 'Electabuzz',
    slug: 'electabuzz',
    types: ['electric'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 0.75,
      female: 0.25,
    },
    hasFemaleImage: false,
    activeSpawn: 'both',
    variants: [],
  },
  {
    id: 126,
    name: 'Magmar',
    slug: 'magmar',
    types: ['fire'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 0.75,
      female: 0.25,
    },
    hasFemaleImage: false,
    activeSpawn: 'night',
    variants: [],
  },
  {
    id: 127,
    name: 'Pinsir',
    slug: 'pinsir',
    types: ['bug'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: ['mega'],
  },
  {
    id: 128,
    name: 'Tauros',
    slug: 'tauros',
    types: ['normal'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 1,
      female: 0,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: [],
  },
  {
    id: 129,
    name: 'Magikarp',
    slug: 'magikarp',
    types: ['water'],
    rarity: 'common',
    catchRate: 255,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: true,
    activeSpawn: 'both',
    variants: [],
  },
  {
    id: 130,
    name: 'Gyarados',
    slug: 'gyarados',
    types: ['water', 'flying'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: true,
    activeSpawn: 'day',
    variants: ['mega'],
  },
  {
    id: 131,
    name: 'Lapras',
    slug: 'lapras',
    types: ['water', 'ice'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: [],
  },
  {
    id: 132,
    name: 'Ditto',
    slug: 'ditto',
    types: ['normal'],
    rarity: 'very rare',
    catchRate: 35,
    genderRatio: null,
    hasFemaleImage: false,
    activeSpawn: 'both',
    variants: [],
  },
  {
    id: 133,
    name: 'Eevee',
    slug: 'eevee',
    types: ['normal'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 0.875,
      female: 0.125,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: [],
  },
  {
    id: 134,
    name: 'Vaporeon',
    slug: 'vaporeon',
    types: ['water'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 0.875,
      female: 0.125,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: [],
  },
  {
    id: 135,
    name: 'Jolteon',
    slug: 'jolteon',
    types: ['electric'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 0.875,
      female: 0.125,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: [],
  },
  {
    id: 136,
    name: 'Flareon',
    slug: 'flareon',
    types: ['fire'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 0.875,
      female: 0.125,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: [],
  },
  {
    id: 137,
    name: 'Porygon',
    slug: 'porygon',
    types: ['normal'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: null,
    hasFemaleImage: false,
    activeSpawn: 'both',
    variants: [],
  },
  {
    id: 138,
    name: 'Omanyte',
    slug: 'omanyte',
    types: ['rock', 'water'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 0.875,
      female: 0.125,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: [],
  },
  {
    id: 139,
    name: 'Omastar',
    slug: 'omastar',
    types: ['rock', 'water'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 0.875,
      female: 0.125,
    },
    hasFemaleImage: false,
    activeSpawn: 'night',
    variants: [],
  },
  {
    id: 140,
    name: 'Kabuto',
    slug: 'kabuto',
    types: ['rock', 'water'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 0.875,
      female: 0.125,
    },
    hasFemaleImage: false,
    activeSpawn: 'night',
    variants: [],
  },
  {
    id: 141,
    name: 'Kabutops',
    slug: 'kabutops',
    types: ['rock', 'water'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 0.875,
      female: 0.125,
    },
    hasFemaleImage: false,
    activeSpawn: 'night',
    variants: [],
  },
  {
    id: 142,
    name: 'Aerodactyl',
    slug: 'aerodactyl',
    types: ['rock', 'flying'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 0.875,
      female: 0.125,
    },
    hasFemaleImage: false,
    activeSpawn: 'both',
    variants: ['mega'],
  },
  {
    id: 143,
    name: 'Snorlax',
    slug: 'snorlax',
    types: ['normal'],
    rarity: 'very rare',
    catchRate: 25,
    genderRatio: {
      male: 0.875,
      female: 0.125,
    },
    hasFemaleImage: false,
    activeSpawn: 'night',
    variants: [],
  },
  {
    id: 144,
    name: 'Articuno',
    slug: 'articuno',
    types: ['ice', 'flying'],
    rarity: 'legendary',
    catchRate: 3,
    genderRatio: null,
    hasFemaleImage: false,
    activeSpawn: 'both',
    variants: ['galarian'],
  },
  {
    id: 145,
    name: 'Zapdos',
    slug: 'zapdos',
    types: ['electric', 'flying'],
    rarity: 'legendary',
    catchRate: 3,
    genderRatio: null,
    hasFemaleImage: false,
    activeSpawn: 'both',
    variants: ['galarian'],
  },
  {
    id: 146,
    name: 'Moltres',
    slug: 'moltres',
    types: ['fire', 'flying'],
    rarity: 'legendary',
    catchRate: 3,
    genderRatio: null,
    hasFemaleImage: false,
    activeSpawn: 'both',
    variants: ['galarian'],
  },
  {
    id: 147,
    name: 'Dratini',
    slug: 'dratini',
    types: ['dragon'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: [],
  },
  {
    id: 148,
    name: 'Dragonair',
    slug: 'dragonair',
    types: ['dragon'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'day',
    variants: [],
  },
  {
    id: 149,
    name: 'Dragonite',
    slug: 'dragonite',
    types: ['dragon', 'flying'],
    rarity: 'rare',
    catchRate: 45,
    genderRatio: {
      male: 0.5,
      female: 0.5,
    },
    hasFemaleImage: false,
    activeSpawn: 'both',
    variants: ['mega'],
  },
  {
    id: 150,
    name: 'Mewtwo',
    slug: 'mewtwo',
    types: ['psychic'],
    rarity: 'legendary',
    catchRate: 3,
    genderRatio: null,
    hasFemaleImage: false,
    activeSpawn: 'both',
    variants: ['megax', 'megay'],
  },
  {
    id: 151,
    name: 'Mew',
    slug: 'mew',
    types: ['psychic'],
    rarity: 'mythical',
    catchRate: 45,
    genderRatio: null,
    hasFemaleImage: false,
    activeSpawn: 'both',
    variants: [],
  },
];
